name: Build and Release Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.15

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: |
          pnpm run build
          pnpm run metadata

      - name: Clean up dev dependencies to shrink archive
        run: rm -rf node_modules

      - name: Package Build Artifacts
        run: |
          tar --exclude='./.git' --exclude='./aiostreams-build.tar.gz' -czf aiostreams-build.tar.gz .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aiostreams-build
          path: aiostreams-build.tar.gz
